### ISSUE TITLE
程序越跑越慢

### ISSUE THREAD

**Issue by opentld** [Postroggy/OC_SORT_CPP#1]
![image](https://github.com/Postroggy/OC_SORT_CPP/assets/21096515/f6d02511-bf07-4921-8bda-500907382cff)
[OCsort.zip](https://github.com/Postroggy/OC_SORT_CPP/files/12536673/OCsort.zip)
重新封装了一下lib库，基本代码没改，只是将调用方式封装了一下。
用yolov7做检测器，运行时，程序跑得越来越慢。
官方的cpp也是这个问题，并且更慢。。。

@Postroggy

**Comment by opentld** [comment]
似乎是与跟踪的目标数量有关？最终大概是7、80ms的样子。。。偶尔会到100多ms。。。

**Comment by Postroggy** [comment]
官方CPP，那个代码提交上去的人偷的我的代码。是的，目标数量增多，程序性能下降还挺严重的，这是先检测后追踪范式的通病，可能优化代码可能解决这个问题。但是我目前是没精力来维护代码。@opentld ，另外你编译优化选项有加吗？

**Comment by opentld** [comment]
> 官方CPP，那个代码提交上去的人偷的我的代码。是的，目标数量增多，程序性能下降还挺严重的，这是先检测后追踪范式的通病，可能优化代码可能解决这个问题。但是我目前是没精力来维护代码。@opentld ，另外你编译优化选项有加吗？

按照 最大优化(优选速度) (/O2) 进行的优化
另外，您能给一些，如何优化代码的建议吗？

**Comment by Postroggy** [comment]
> 按照 最大优化(优选速度) (/O2) 进行的优化 另外，您能给一些，如何优化代码的建议吗？

你可以用profiler分析一下程序性能瓶颈在哪，另外，我当时写代码的时候觉得 [freeze()](https://github.com/Postroggy/OC_SORT_CPP/blob/b64e2e6e254d7f33f7123550b1f8b3de3ee416b6/src/kalmanfilter.cpp#L154) 是可以进一步优化的，还有你可以更换eigen的数据类型，或者更换Eigen的后端，比如用intel的MKL。如果是MSVC的话，可以加上编译选项`/openmp`开多线程并行计算。我觉得可能的优化方向是内存管理和加速计算上。

你可以继续看看代码应该优化的空间还是有的。
