### ISSUE TITLE
当需要跟踪的目标变多时，会变得很慢

### ISSUE THREAD

**Issue by uglymie** [Postroggy/OC_SORT_CPP#2]
我测试了一个视频，发现当需要跟踪的目标变多时，会变得很慢，是OCSORT算法本身的限制吗？

**Comment by Postroggy** [comment]
你好，不是OCSORT算法本身问题，是我代码的问题。已经修复 [commit history](https://github.com/Postroggy/OC_SORT_CPP/commit/887a1c3f7eaa82fd093015037d3a076d44a5cd22)
