### ISSUE TITLE
Issue in kalmanfilter.cpp

### ISSUE THREAD

**Issue by alexemme** [Postroggy/OC_SORT_CPP#3]
Hello, 
i found a bug in your code on kalmanfilter.cpp, row 56:
P = _alpha_sq * ((F * P), F.transpose()) + Q;

there should be a "*" in the place of the ",":
P = _alpha_sq * ((F * P) * F.transpose()) + Q;

**Comment by Postroggy** [comment]
truly, you are right. 
If you can issue a pull request, that would be good.

**Comment by Postroggy** [comment]
bug fixed.
