### ISSUE TITLE
可以麻烦您将cpp对应的py文件推到这个仓库上吗

### ISSUE THREAD

**Issue by dujifeng** [Postroggy/OC_SORT_CPP#5]
请问您是否还记得您写的ocsort.cpp对应的官方的py文件的commitment id, 或者可以麻烦您将cpp对应的py文件推到这个仓库上吗，这样可以比较好的做一个对应。根据最新官方库的commitment，似乎和cpp有些对不上

**Comment by Postroggy** [comment]
当时我写这个库的时候，已经毕业工作了，然后有一个人抄原封不动了我的代码pr到官方代码库上面去了，见[link](https://github.com/noahcao/OC_SORT/commit/cabf46ace8684e771d94b6adece926fd2b6f52df) 。
